### PR TITLE
Port to Linux

### PR DESCRIPTION
**Pull request by PaulBGD**
If you want to test it, just run ./linux/capture.sh with the same arguments that you'd pass to the swift binary.

### CODE REVIEW

**Comment by PaulBGD** [comment]
This can easily be ported to Mac, replacing all of the Swift code. The changes we'd need to make to the bash script are here: https://trac.ffmpeg.org/wiki/Capture/Desktop#OSX

**Comment by matheuss** [comment]
@PaulBGD thank you for the PR!

I'm afraid we can't use `ffmpeg` for the job – at least on macOS. I spent countless hours on it (`history | grep ffmpeg | wc -l` currently returns 839 😛) and I'm almost sure that it isn't a viable solution:

Recording the entire screen with `ffmpeg -f avfoundation -i 1 -y test.mp4`:

ffmpeg

Recording the entire screen with `aperture.js`:

aperture

Besides that, we can't record a section of the screen with `ffmpeg` on macOS 😕 

It would be awesome if you could gather some benchmarks from ffmpeg on Linux 😄 Also, do you know how to record the screen natively on Linux, like I did with Swift?

**Comment by PaulBGD** [comment]
Yeah we could do it native, but ffmpeg is incredibly fast on Linux. I'll grab some benchmarks.

**Comment by doot0** [comment]
Yo @PaulBGD, I'm curious about those benchmarks - have you had any time to run any? 😅

**Comment by PaulBGD** [comment]
I tested the ffmpeg implementation, but I'm working on a native implementation to compare them to.
ffmpeg could record 345 frames using 1 CPU core, but I'm running that on a pretty powerful system so I don't know how it compares.

**Comment by PaulBGD** [comment]
This is ready to go!

**Pull request closed without merging**
